logging:
  level:
    blog: WARN
    org: WARN
    sql: debug
#    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor: TRACE


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
  sql:
    init:
      mode: always


mail:
  host: "localhost"
  port: 1025
  username: ${MAIL_HOST_USERNAME}
  password:  ${MAIL_HOST_PASSWORD}
